# Change baseurl before deploy
baseurl = "https://miori3.github.io/via.chair.github.io/"
locale  = "en-us"
title   = "via.chair"
[params]
navbar_title = "Via Chair"
homeTitle = "Via Chair"


# Theme i18n support
# See all available values at https://github.com/CaiJimmy/hugo-theme-stack/tree/master/i18n
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
disqusShortname = "via"

[pagination]
    pagerSize = 5
